### PR TITLE
prevent sequence build fail on Ubuntu 18.04+

### PR DESCRIPTION
**Pull request by curiositycasualty**
#### Rationale
Unable to build the sequencing tools with modern versions of Ubuntu.

In lieu of a more sophisticated platform/version detection mechanism, this compares the major version of `VERSION_ID` from `/etc/os-release` against `18` while defaulting to the plain `./configure` command. `/etc/os-release` should be available on all modern systemd based systems, but I've wrapped under `apt-get` protection since it's more reliably on Debian/Ubuntu systems.

Without this:
```
make[3]: Entering directory '<snip>/SequenceAnalysis/pipeline_code/build/tool_src/fastx_toolkit-0.0.13.2/src/fasta_formatter'
g++ -DHAVE_CONFIG_H -I. -I../.. -I/usr/include/gtextutils -I../libfastx     -g -O2 -Wall -Wextra -Wformat-nonliteral -Wformat-security -Wswitch-default -Wswitch-enum -Wunused-parameter -Wfloat-equal -Werror -DDEBUG -g -O1 -DDEBUG -g -O1 -MT fasta_formatter.o -MD -MP -MF .deps/fasta_formatter.Tpo -c -o fasta_formatter.o fasta_formatter.cpp
fasta_formatter.cpp: In function ‘void parse_command_line(int, char**)’:
fasta_formatter.cpp:105:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
  105 |    usage();
      |    ~~~~~^~
fasta_formatter.cpp:107:3: note: here
  107 |   case 'i':
      |   ^~~~
cc1plus: all warnings being treated as errors
make[3]: Leaving directory '<snip>/SequenceAnalysis/pipeline_code/build/tool_src/fastx_toolkit-0.0.13.2/src/fasta_formatter'
make[3]: *** [Makefile:315: fasta_formatter.o] Error 1
make[2]: Leaving directory '<snip>/SequenceAnalysis/pipeline_code/build/tool_src/fastx_toolkit-0.0.13.2/src'
make[2]: *** [Makefile:290: all-recursive] Error 1
make[1]: Leaving directory '<snip>/SequenceAnalysis/pipeline_code/build/tool_src/fastx_toolkit-0.0.13.2'
make[1]: *** [Makefile:318: all-recursive] Error 1
make: *** [Makefile:249: all] Error 2
```

### CODE REVIEW

**Comment by curiositycasualty** [comment]
The [travis failure](https://travis-ci.com/github/BimberLab/DiscvrLabKeyModules/builds/191033646#L1375-L1376) seems unrelated to my changes:
```
./travis.sh: line 113: GH_TOKEN: unbound variable
The command "bash ./travis.sh" exited with 1.
```

**Comment by bbimber** [comment]
@curiositycasualty thanks for the PR. It seems simple enough but I have a couple comments/questions:

this is somewhat timely b/c I've been thinking about reviewing this archane, monolithic install script. How are you using these modules and is there a scheme that's more useful to you? for example, I'm pondering splitting up the various tools, and possibly making some kind of automatic dockerhub build.  

second, if you use the newer fastxtoolkit (http://hannonlab.cshl.edu/fastx_toolkit/download.html), does it work more out-of-the box?

**Comment by bbimber** [comment]
@curiositycasualty, I didnt pick up that you work at LabKey, this makes a whole lot more sense. anyway, I'd still like to move this to a better scheme that than single install script

**Comment by bbimber** [comment]
@curiositycasualty yes, with respect to travis, it is expecting GH_TOKEN defined, and that's probably linked to my account. typically a finite number of accounts are kicking off these builds - it would not surprise me if there weak aspects that were not that robust.

**Comment by curiositycasualty** [comment]
Was the monochromatic avatar not a give away? 😂

There's definitely plenty of room for improvement in the script. But I was trying here to make a minimal change just to get over the Ubuntu 18.04+ hump.

**Comment by bbimber** [comment]
sure, fair enough. i dont have an ubuntu instance, but does this (newer toolkit version) work:

    wget $WGET_OPTS https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2
    bunzip2 fastx_toolkit-0.0.14.tar.bz2
    tar -xf fastx_toolkit-0.0.14.tar
    echo "Compressing TAR"
    bzip2 fastx_toolkit-0.0.14.tar
    cd fastx_toolkit-0.0.14
    ./configure --prefix=$LK_HOME
    make
    make install

I dont suppose you have any recommendations (maybe schemes used at LK) that I could refactor this into?

**Comment by curiositycasualty** [comment]
Bash is my bag. But refining this script felt a lot outside the scope of "get it working on Ubuntu 18.04+".

I can recommend some general things though:
  - I live and die by [shellcheck](https://github.com/koalaman/shellcheck) there's frequently "linting" support in major IDEs that support this
  - similarly, [strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode) -- but it seems like that's mostly already in there
  - normally when I have to do things like this, I batch all downloads towards the start so that I'm not 30 minutes into the script before I find out a url is invalid

**Comment by curiositycasualty** [comment]
Ran into the same thing with https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2

**Comment by bbimber** [comment]
Yeah, i'm not expecting you to implement any changes - just seeing if there are existing tools or schemes at LK I could move toward.  In theory i would have more like a 'recipe' per tool, and then my dev/test instance might declare which dependencies it needs. 

Anyway, were you by chance able to test that newer of the tool, to see if maybe we have a simpler fix?

**Comment by curiositycasualty** [comment]
The newer version of the tool still results in the same compilation error:
```
fasta_formatter.cpp: In function ‘void parse_command_line(int, char**)’:
fasta_formatter.cpp:105:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
  105 |    usage();
      |    ~~~~~^~
fasta_formatter.cpp:107:3: note: here
  107 |   case 'i':
      |   ^~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:425: fasta_formatter.o] Error 1
make[3]: Leaving directory '/tmp/build/tool_src/fastx_toolkit-0.0.14/src/fasta_formatter'
make[2]: *** [Makefile:373: all-recursive] Error 1
make[2]: Leaving directory '/tmp/build/tool_src/fastx_toolkit-0.0.14/src'
make[1]: *** [Makefile:411: all-recursive] Error 1
make[1]: Leaving directory '/tmp/build/tool_src/fastx_toolkit-0.0.14'
make: *** [Makefile:342: all] Error 2
```

**Comment by bbimber** [comment]
@curiositycasualty ok, thanks. i will try a little with docker shortly, but i imagine your proposal will be fine.

**Comment by bbimber** [comment]
@curiositycasualty I have a simpler solution. after reviewing this, we're not using fastx_toolkit anymore, plus this software isnt maintained. we can actually just drop it.

I committed that change to 20.7, and opened a PR here:

https://github.com/LabKey/DiscvrLabKeyModules/pull/68/files
